---

- import_tasks: common.yml

- name: Download automake
  get_url:
      url={{ automake_url }}
      dest={{ pkgsdir }}/{{ automake_file }}

- name: Unpack automake
  unarchive:
      src={{ pkgsdir }}/{{ automake_file }}
      dest={{ builddir }}
      remote_src=yes
