---

- import_tasks: common.yml

- name: Install dependencies on Ubuntu
  apt:
      name: autoconf,automake,binutils-dev,bison,build-essential,cmake,g++,gawk,git,libboost-dev,libboost-filesystem-dev,libboost-program-options-dev,libboost-regex-dev,libboost-system-dev,libboost-thread-dev,libboost-context-dev,libbz2-dev,libc-client-dev,libldap2-dev,libc-client2007e-dev,libcap-dev,libcurl4-openssl-dev,libdwarf-dev,libelf-dev,libexpat-dev,libgd2-xpm-dev,libgoogle-glog-dev,libgoogle-perftools-dev,libicu-dev,libjemalloc-dev,libmcrypt-dev,libmemcached-dev,libmysqlclient-dev,libncurses-dev,libonig-dev,libpcre3-dev,libreadline-dev,libtbb-dev,libtool,libxml2-dev,zlib1g-dev,libevent-dev,libmagickwand-dev,libinotifytools0-dev,libiconv-hook-dev,libedit-dev,libiberty-dev,libxslt1-dev,ocaml-native-compilers,libsqlite3-dev,libyaml-dev,libgmp3-dev,gperf,libkrb5-dev,libnotify-dev,libpq-dev
      state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install dependencies on Redhat
  yum:
      name: zlib-devel,bzip2-devel,python-devel,libtool,curl-devel,libicu-devel,tbb-devel,openssl-devel,libdwarf,elfutils-libelf-devel,libcap-devel,gperftools-libs,gmp-devel,ImageMagick,libxslt-devel,readline-devel,libmemcached,expat-devel,libyaml,binutils-devel,openldap-devel
      state: present
  when: ansible_distribution == 'RedHat'

- include_tasks: automake.yml
  when: ansible_distribution == 'RedHat'

- name: Download hhvm
  shell:
      cd {{ builddir }};
      git clone {{ hhvm_url }};
      cd hhvm;
      git submodule update --init --recursive

- name: Build hhvm
  shell:
      cd {{ builddir }}/hhvm;
      cmake -DCMAKE_INSTALL_PREFIX={{ installdir }} -DMYSQL_UNIX_SOCK_ADDR=/var/run/mysqld/mysqld.sock .;
      make -j{{ ansible_processor_count }};
      make install

- name: Copy hhvm service
  template:
      src: hhvm/hhvm.service
      dest: /lib/systemd/system/hhvm.service

- name: Make hhvm config
  file:
      path: "{{ hhvm_conf_path }}"
      state: directory
      mode: 0755

- name: Copy hhvm.hdf
  template:
      src: hhvm/hhvm.hdf
      dest: "{{ hhvm_conf_path }}/hhvm.hdf"

- name: hhvm runtime dir
  file:
      path: "{{ hhvm_run_path }}"
      state: directory
      mode: 0755
      owner: root
      group: root

- name: hhvm log dir
  file:
      path: "{{ hhvm_log_path }}"
      state: directory
      mode: 0755
      owner: root
      group: root

- name: Copy server.ini
  template:
      src: hhvm/server.ini
      dest: "{{ hhvm_conf_path }}/server.ini"

- name: Copy php.ini
  template:
      src: hhvm/php.ini
      dest: "{{ hhvm_conf_path }}/php.ini"

- name: Start hhvm service
  service:
      name: hhvm
      state: started
      enabled: yes

  #  shell:
  #    "{{ installdir }}/bin/hhvm --mode daemon --config {{ hhvm_conf_path }}/server.ini --config {{ hhvm_conf_path }}/php.ini --config {{ hhvm_conf_path }}/hhvm.hdf"
